apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassname: standard
  accessModes:
    - ReadWriteOnce #Only Claim by ONE Node
 #   - ReadonlyMany #Can be Claim by mutliple Nodes
 #   - ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate